server:
  port:
    10006
spring:
  application:
    name: member-service-nacos-provider #名称，可以自己指定　
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:8889/e_commerce_center_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 361232
  #配置nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置nacos Server的地址
#配置暴露所有的监控点
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
    mapperLocations: classpath:mapper/*.xml #后面 mapper 文件的位置
    type-aliases-package: com.zsy.entity


