server:
  port: 80

spring:
  application:
    name: member-service-consumer-80
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1


eureka:
  client:
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka,http://eureka9002.com:9002/eureka
    register-with-eureka: true
    fetch-registry: true