server:
  port: 10010
spring:
  application:
    name: seata-storage-micro-service
  cloud:
    alibaba:
      seata:
        tx-service-group: hspedu_order_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:8889/storage_micro_service?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 361232
logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml